import { ChatList } from "@/features/dashboard/messages/components/ChatList";
import { getCachedUser } from "@/lib/redis";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Messages",
  description: "Generated by create next app",
};

export default async function RecruiterLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCachedUser();
  return (
    <div>
      <div className="ml-3  w-full lg:w-[83vw] overflow-auto flex  dark:bg-gray-900">
        {/* Chat List Sidebar */}
        <div className="w-80 hidden lg:block   ">
          <ChatList user={user} />
        </div>
        {children}
      </div>
    </div>
  );
}
