import { Header } from "@/components/Navbar";
import { Sidebar } from "@/components/Sidebar";
import ThemeProviderWrapper from "@/components/ThemeProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ReactQueryProvider } from "@/lib/ReactQueryProvider";
import { getCachedUser } from "@/lib/redis";
import type { Metadata } from "next";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCachedUser();
  return (
    <ThemeProviderWrapper>
      <ReactQueryProvider>
        <TooltipProvider>
          <div className="min-h-screen grid grid-cols-[80px_1fr] lg:grid-cols-[250px_1fr]">
            {/* Sidebar always visible, left */}
            <aside className="sticky top-0 left-0 h-screen z-50">
              <Sidebar />
            </aside>

            {/* Right side: header + content stacked */}
            <div className="flex flex-col min-h-screen">
              {/* Header sticky top */}
              <header className="sticky top-0 z-40 bg-white">
                <Header
                  email={user?.email}
                  img={user?.img || ""}
                  uId={user?.id}
                />
              </header>

              {/* Children */}
              <main className="flex-1">{children}</main>
              <Toaster richColors />
            </div>
          </div>
        </TooltipProvider>
      </ReactQueryProvider>
    </ThemeProviderWrapper>
  );
}
