import { Toaster } from "@/components/ui/toaster";
import { DashNavbar } from "@/features/dashboard/components/DashNavbar";
import Mainpage from "@/features/dashboard/components/Mainpage";
import { authUser, CheckUser } from "@/lib/Actions/Users";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await authUser();
  const checkUser = await CheckUser(user.email || "");
  if (!checkUser.data) {
    redirect("/user/onboarding");
  }
  return (
    <div>
      <DashNavbar />
      <div className="m-10">
        <div className="">
          <h1 className="text-4xl font-bold tracking-tight">Dashboard</h1>
        </div>
        <div className="">
          <h1 className="text-sm font-semibold text-gray-400">Welcome,sohan</h1>
        </div>
        <Mainpage />
        <main>{children}</main>
        <Toaster />
      </div>
    </div>
  );
}
