import { DashNavbar } from "@/components/pages/dashboard/DashNavbar";
import Mainpage from "@/components/pages/dashboard/Mainpage";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <DashNavbar />
      <div className="m-10">
        <div className="">
          <h1 className="text-4xl font-bold tracking-tight">Dashboard</h1>
        </div>
        <div className="">
          <h1 className="text-sm font-semibold text-gray-400">Welcome,sohan</h1>
        </div>
        <Mainpage />
        <main>{children}</main>
        <Toaster />
      </div>
    </div>
  );
}
